# List of plugins

# tmux plugin manager (tpm) REQUIRED!!
set -g @plugin 'tmux-plugins/tpm'

# list of sensible settings (better delay times, better term colors, better pane switching [can hold ctrl and quickly do b + p or b + n without releasing ctrl])
set -g @plugin 'tmux-plugins/tmux-sensible'

# dracula theme
set -g @plugin 'dracula/tmux'

# Powerline Status line
set -g @plugin 'erikw/tmux-powerline'

# copy tmux text with vim yank (y)
set -g @plugin 'tmux-plugins/tmux-yank'

# navigate between panes with <C-h/j/k/l> vim motions
set -g @plugin 'christoomey/vim-tmux-navigator'

# search windows with fzf
set -g @plugin 'sainnhe/tmux-fzf' # prefix + f

# tmux menu - shortcut: prefix + /
# https://github.com/jaclu/tmux-menus/tree/bc8e42f601f6c038ed23f68a4a086607a91a8d46
set -g @plugin 'jaclu/tmux-menus'
set -g @menus_trigger '/' # set menu shortcut to prefix + /

# which key for tmux: https://github.com/alexwforsythe/tmux-which-key
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'a'
set -g @sessionx-window-mode 'on'

set -g @dracula-show-powerline true
set -g @dracula-plugins "git"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-cpu-display-load true
set -g @dracula-cpu-usage-label "CPU"
set -g @dracula-show-empty-plugins false

set -g main-pane-height "85%"

set -g status-position top

set -g mouse on

# set window name to current directory
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# vim hjkl window movements
# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind-key k new-window \; split-window -v -p	15 \; select-pane -U 

# sesh tmux-fzf setup
bind-key "T" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
